import Footer from "@/components/Footer";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/header/Header";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Movie",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { lang } }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-body  font-[Sora] text-white`}>
        <Header />
        <main>
          <div className="container grid lg:grid-cols-[218px_1fr] gap-[3.5rem]">
            <Sidebar lang={lang} />
            <div className="content">{children}</div>
          </div>
        </main>
        <div id="modal-content"></div>
        <Footer />
      </body>
    </html>
  );
}
